name: Pyrefly Type Check

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run Pyrefly Type Checker
        run: uv run pyrefly check --output-format=github
